-- Active: 1749830440641@@127.0.0.1@3306@mysql

CREATE DATABASE teams;
USE teams;
CREATE TABLE persons(
  name VARCHAR(20),
  age INTEGER,
  height INTEGER
);

SHOW DATABASES;
SELECT DATABASE();

SELECT USER(), CURRENT_USER();

SELECT VERSION();

SHOW GRANTS FOR CURRENT_USER;

CREATE DATABASE test1;
USE test1;
CREATE DATABASE test2;
USE test2;
CREATE DATABASE test3;
USE test3;

DROP DATABASE test1;
DROP DATABASE test2;
DROP DATABASE test3;